### ISSUE TITLE
Information about MODA

### ISSUE THREAD

**Issue by llrs** [fairmiracle/MODA#1]
I would like to read more about the package, I found the preprint, but is there a published article of the package?

As a technical notes on the package:
When loading the package I get two warnings, see the vignette for instance. 
In WeightedModulePartitionAmoutain and in WeightedModulePartitionLouvain there are `print` functions instead of a `message` to the user which confused me initially. 

Many thanks

**Comment by fairmiracle** [comment]
@llrs Thanks for your interest. The manuscript is still in preparing and I will change the `print` in next update. 

If you have any doubts just drop me an email or comment here.
